version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - app-tier

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
    ports:
      - '26379:26379'
    networks:
      - app-tier

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.1'
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - app-tier
